### ISSUE TITLE
This library doesn't do what it says it does...

### ISSUE THREAD

**Issue by cjw296** [bob1de/with_contextvars#1]
This library advertises itself as providing context manager support for `ContextVar` but it doesn't really do that.

The context manager support expected would be to enter a new context and do the same as `Context.run`.
There is an [open PR against cpython](https://github.com/python/cpython/issues/99633) to do this.

This library appears to just set variables in the _current_ context on entry and then reset them on exist, which is very different to creating a new context and running the code in it...

**Comment by bob1de** [comment]
Hello,

I'm not quite sure how you came to expect this library to behave like `Context.run`.
That's what both README and docstring say:

> This module provides ``Set``, a context manager which sets one or more ``contextvars``
> variables upon activation and resets them to their previous values at exit.

I find this pretty clear. You pass it `ContextVar` objects and values which are then stacked onto the current context, not a pre-composed, isolated `Context` object.

So, in other words, it's syntactic sugar for setting context variables, not for activating a context.

HTH. Feel free to keep commenting if you have anything to add.

Best regards

**Comment by cjw296** [comment]
I think it's this test from the readme that I have a problem with: "However, using contextvars.Context.run() is more efficient and should be preferred where possible.": it's not that `run()` is more efficient, it's doing something fundamentally different: replacing the current `Context` with the one that `run` is an attribute of and then working in there, seems orthogonal to what this package does?

**Comment by bob1de** [comment]
I see that this wording might be a bit unfortunate.
The "where possible", together with the fact that you feed `ContextVar` objects instead of a `Context` to this library to begin with, seemed clear enough to me to tell the difference.
Never even thought of this as a replacement for `Context.run()`.

So, when you just want a bunch of variables to be safely set/reset around some passage of code, this library saves you a few lines and possible source of error.
On the other hand, if your use case allows building an isolated `Context` with everything needed beforehand, and possibly even reusing that, `Context.run()` is generally more efficient than stacking the variables one by one upon each activation.
That's what it meant to say.

Anyway, thanks for pointing that out, I'll have this aspect documented more clearly.

Best regards
